export const produtosImagens: Record<string, string> = {
  'Red Bull 250ml': '/produtos/redbull250.png',
  'Red Bull 473ml': '/produtos/redbull473.png',
  'Água c/ Gás': '/produtos/agua-gas.png',
  'Refri 200ml': '/produtos/refri200.png',
  'Água de coco 250ml': '/produtos/agua-coco-250.png',
  'Suco laranja 250ml': '/produtos/suco-laranja-250.png',
  'Suco uva 250ml': '/produtos/suco-uva-250.png',
  'Barrinha Pinati': '/produtos/pinati.png',
  'Barrinha NUTS': '/produtos/nuts.png',
  'Bold 40g': '/produtos/bold-40.png',
  'Bold 60g': '/produtos/bold-60.png',
  'Ovinho': '/produtos/ovinho.png',
  'EQLIBRI': '/produtos/eqlibri.png',
  'Trento': '/produtos/trento.png',
  'Baton': '/produtos/baton.png',
  'Bubbaloo': '/produtos/bubbaloo.png',
  'Talento 25g': '/produtos/talento-25.png',
  'Geladinho americano': '/produtos/geladinho.png',
  'Lacta ao leite 20g': '/produtos/lacta-ao-leite-20.png',
  'Prestígio': '/produtos/prestigio.png',
  'Paçoquita': '/produtos/pacoquita.png',
  'Trident X': '/produtos/trident-x.png',
  'Mentos Pure': '/produtos/mentos-pure.png',
  'Marmita 300g': '/produtos/marmita_300.png',
  'marmita 300g': '/produtos/marmita_300.png',
  'Marmita300g': '/produtos/marmita_300.png',
  'Marmita 370g': '/produtos/marmita_370.png',
  'marmita 370g': '/produtos/marmita_370.png',
  'Marmita370g': '/produtos/marmita_370.png',
}
